# Generated by Django 5.2.10 on 2026-01-20 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('identifier', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('ON', 'Activo'), ('OFF', 'Inactivo'), ('MNT', 'Mantenimiento'), ('ERR', 'Error')], default='OFF', max_length=3)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SensorType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('unit', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('capacity', models.PositiveIntegerField(default=1)),
                ('location', models.CharField(max_length=255)),
                ('current_status', models.CharField(choices=[('AVAIL', 'Disponible'), ('RESV', 'Reservado'), ('OCCUNR', 'Ocupado sin reserva'), ('RESOCC', 'Reservado y ocupado'), ('MAINT', 'Mantenimiento')], default='AVAIL', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpaceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('identifier', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('ON', 'Activo'), ('OFF', 'Inactivo'), ('MNT', 'Mantenimiento'), ('ERR', 'Error')], default='OFF', max_length=3)),
                ('last_value', models.FloatField(blank=True, null=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='spaces.device')),
                ('sensor_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='spaces.sensortype')),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='spaces.space'),
        ),
        migrations.AddField(
            model_name='space',
            name='space_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='spaces.spacetype'),
        ),
    ]
